### ISSUE TITLE
Implement State with the Conversations stream

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-messagebird#17]
@visch seems like the only way to limit what's fetched is via the offset and limit.

I did see this in the documentation `Retrieves all conversations sorted by the lastReceivedDatetime` - so maybe there's some filtering on the tap side that could happen in a separate iteration.

_Originally posted by @tayloramurphy in https://github.com/MeltanoLabs/tap-messagebird/issues/16#issuecomment-1399015938_

**Comment by pnadolny13** [comment]
From a quick look at the docs this looks similar to an issue that Prratek and Omar are running into with Stripe (slack [thread 1](https://meltano.slack.com/archives/C01PKLU5D1R/p1681998358444049) and [2](https://meltano.slack.com/archives/C01PKLU5D1R/p1639760305331600)). The Stripe API returns most recent transactions first and doesnt allow sorting although it does allow a start/end timestamps so theyre trying to paginate time range chunks starting at the oldest first. Their hope is that making it pseudo sorted like this will allow their streams to be resumable which solves a problem they had with long backfills failing before they could save an incremental key.

It seems like you can do something similar although only having an offset is a little tricky. I wonder if it accepts like a -1 to offset max, otherwise offsetting a huge number to try to get the beginning of time.

**Comment by visch** [comment]
> 

Yeah something like that when I see the data set it'll be easier to pick the right solution here too as it's either heavy co

> From a quick look at the docs this looks similar to an issue that Prratek and Omar are running into with Stripe (slack [thread 1](https://meltano.slack.com/archives/C01PKLU5D1R/p1681998358444049) and [2](https://meltano.slack.com/archives/C01PKLU5D1R/p1639760305331600)). The Stripe API returns most recent transactions first and doesnt allow sorting although it does allow a start/end timestamps so theyre trying to paginate time range chunks starting at the oldest first. Their hope is that making it pseudo sorted like this will allow their streams to be resumable which solves a problem they had with long backfills failing before they could save an incremental key.
> 
> It seems like you can do something similar although only having an offset is a little tricky. I wonder if it accepts like a -1 to offset max, otherwise offsetting a huge number to try to get the beginning of time.

I think it's a little easier here due to 
```
Retrieves all conversations sorted by the lastReceivedDatetime field so that all conversations with new messages appear first.
``` 

https://developers.messagebird.com/api/conversations/#list-conversations

But we shall see! Waiting on access to some production data then we should be able to do this quickly!
